#! /bin/sh

feh --bg-fill /home/jensenlai/Pictures/portal.png

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V

bspc config border_width         5 
bspc config window_gap           15
bspc config focused_border_color  \#8defbb

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Emacs state=tiled
bspc rule -a Surf state=tiled

xsetroot -cursor_name left_ptr
/home/jensenlai/.config/polybar/launch.sh
picom --experimental-backends -b 
dunst &
